-- require("items.apple")
-- require("items.menus")
-- require("items.menus")
-- require("items.spaces")
-- require("items.space_mode")
-- require("items.front_app")
require("items.calendar")
require("items.battery")
require("items.bluetooth")
require("items.cpu")
require("items.ram")
require("items.wifi")
-- require("items.widgets")
require("items.media")
