#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all icons
source "$CONFIG_DIR/userconfig.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="JetbrainsMono Nerd Font:Bold:15.0"
ICON_FONT="SF Pro:Semibold:15.0"


# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker


BAR_PROPS=(
  height=37
  blur_radius=30
  position=bottok
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR
)

DEF_PROPS=(
  icon.font="$ICON_FONT:Regular:16.0"
  icon.color=$WHITE
  icon.padding_left=10
  icon.padding_right=10
  label.font="$FONT"
  label.color=$WHITE
  label.padding_right=10
  background.color=$BG_PRI_COLOR
  background.padding_right=6
  background.height=22
  background.corner_radius=8
)

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --bar "${BAR_PROPS[@]}" 
sketchybar --default "${DEF_PROPS[@]}" 

#sketchybar --animate sin 30 --bar y_offset=100 y_offset=10

# -- Left Side Items --
#source "$ITEM_DIR/ubuntu_menu.sh"
sketchybar --add item cat left \
           --set cat icon="≽^•⩊•^≼"\
                     icon.font="$ICON_FONT:Regular:18.0"\
                     icon.color=$WHITE\
                     icon.padding_right=-10\
                     label.draw=off

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# -- Right Side Of Notch Items --
source "$ITEM_DIR/media.sh"

# -- Right Side Items --
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/cpu.sh"


##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
